### PR TITLE
Formula terms

### LINKED ISSUE #242: Incorrect `formula_terms` in output netCDF files in some cases
When a domain ancillary construct with bounds is the same netCDF variable as the parent dimension coordinate constructs, the domain ancillary construct is erroneously written to an output file in addition to the dimension coordinate construct.

```python
>>> import cfdm
>>> cfdm.environment(paths=False)
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
HDF5 library: 1.12.1
netcdf library: 4.8.1
Python: 3.10.8
netCDF4: 1.6.0
numpy: 1.23.5
cfdm.core: 1.10.0.2
cftime: 1.6.2
netcdf_flattener: 1.2.0
cfdm: 1.10.0.2
```

### PR DESCRIPTION
**Pull request by davidhassell**
Fixes #242

### CODE REVIEW

**Comment by davidhassell** [comment]
Test added, as per @sadielbartholomew's suggestion. Thanks!

**Review by sadielbartholomew — APPROVED** [review]
Working fix with a robust new test. The full test suite passes locally for me on this branch, indicating also that the effects of adjustments made to `example_field(1)` have been accounted for properly.

Perfect, please merge.

**Comment by sadielbartholomew** [comment]
Just thinking though that the tweaks to the `example_field(1)` here might effect the cf-python test results downstream, so I'll run the test suite there to check in case anything needs adjusting. (Unless you've already checked for this David, in which case let me know, but a second check won't hurt.)

**Comment by sadielbartholomew** [comment]
> so I'll run the test suite there to check in case anything needs adjusting

Nope, it's all good and passing there. So we can ignore my previous comments (except for the main review which stands).

**Pull request merged**
