### PR TITLE
Test update to GitHub Actions (Codecov coverage reports)

### PR DESCRIPTION
**Pull request by sadielbartholomew**
Updates to our workflow to run the test suite, aiming to upload a coverage report to Codecov for two jobs, one each for the latest distros for Ubuntu and Mac using Python 3.7 as a representative Python version (I think it would be superfluous & a waste of Actions jobs to upload further coverage reports, since each job should give a very similar if not identical figure).

Testing in this PR to try to get the two coverage reports to show as a pair of 'checks' tied to the PR. Once I get that working, I can merge the PR.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
Opening & closing to re-trigger...

**Comment by sadielbartholomew** [comment]
There is something not quite right with the coverage report upload step so I need to tweak something to ensure the XML report gets picked up:

```
bash codecov.sh -f ./coverage.xml -s ./cfdm_coverage_reports -n codecov-umbrella -F unittests -Z -q ./cfdm_coverage_reports/codecov_report.gz

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20200917-4e8f14b


==> GitHub Actions detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    - file not found at ./coverage.xml
--> No coverage data found.
    Please visit http://docs.codecov.io/docs/supported-languages
    search for your projects language to learn how to collect reports.
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
```

**Comment by sadielbartholomew** [comment]
Will pick this up again on Monday...

**Comment by sadielbartholomew** [comment]
```

```

**Comment by sadielbartholomew** [comment]
The latest commit solves the issues with the XML not being detected. Now seeing the following error, which implies a token is needed:

```
Run codecov/codecov-action@v1.0.6
bash codecov.sh -f ./cfdm/test/cfdm_coverage_reports/coverage.xml -n codecov-umbrella -F unittests -Z

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20200917-4e8f14b


x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./cfdm/test/cfdm_coverage_reports/coverage.xml bytes=373622
==> Appending adjustments
    https://docs.codecov.io/docs/fixing-reports
    -> No adjustments found
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=&commit=60a38abed39491e884fef32086d692617aaf25b2&build=&build_url=&name=codecov-umbrella&tag=&slug=NCAS-CMS%2Fcfdm&service=&flags=unittests&pr=&job=&cmd_args=f,n,F,Z
->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200917-4e8f14b&token=secret&branch=&commit=60a38abed39491e884fef32086d692617aaf25b2&build=&build_url=&name=codecov-umbrella&tag=&slug=NCAS-CMS%2Fcfdm&service=&flags=unittests&pr=&job=&cmd_args=f,n,F,Z
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
##[error]Codecov failed with the following error: The process 'bash' failed with exit code 1
```

But since this repo is public and we are using GH Actions, the docs clearly state no token should be required. Investigating now...

**Comment by sadielbartholomew** [comment]
Had a skim through the Codecov support forum and some of their docs, but nothing sticks out as being wrong with the relevant workflow step.

I now suspect the HTTP 400 response may be due an access issue between Codecov and the repo since it still says 'Access request pending' against the NCAS-CMS organisation under Codecov's organisation access listing on my settings.

Will request permission and hopefully get it working to upload the coverage reports on Friday after my leave.

**Comment by jdtoombs** [comment]
Just wanted to pay it forward - ended up getting the solution [here ](https://github.com/hyperledger/aries-framework-go/pull/2206) thanks to @llorllale

**Comment by sadielbartholomew** [comment]
@jdtoombs ah, thank you so much for the heads up! I thought I was using the latest version of the Action but it seems 1.0.7 was still far from it. I've just re-run with version 1.0.13 and it has worked. Fantastic, cheers :grinning:

**Comment by sadielbartholomew** [comment]
Usually I would squash the final (here, four) 'fix' commits into one before merging, but since they serve as a nice record of the Codecov Action issue I will preserve them (e.g. as a reminder that it seems we can't specify just @v1 to get the latest version, we need to explicitly provide @v1.X so some updating may be required in future to patch bugs or issues in the upstream Action).

**Pull request merged**
